version: '2'
services:
    plants-app:
        image: plants
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://plants-postgresql:5432/plants
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    plants-postgresql:
        extends:
            file: postgresql.yml
            service: plants-postgresql
